# Generated by Django 4.0.6 on 2022-07-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=50)),
                ('capital', models.CharField(blank=True, default=None, max_length=50)),
                ('region', models.CharField(blank=True, default=None, max_length=50)),
                ('subregion', models.CharField(blank=True, default=None, max_length=50)),
                ('population', models.PositiveBigIntegerField(default=0)),
                ('languages', models.JSONField(blank=True, default=list)),
                ('currencies', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
