# Generated by Django 4.0.6 on 2022-07-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0002_alter_country_capital_alter_country_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
