# Generated by Django 4.0.6 on 2022-07-13 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_alter_country_options_alter_country_currencies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='languages',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
